### ISSUE TITLE
Is it possible to run AWS Batch Jobs?

### ISSUE THREAD

**Issue by ogoid** [knowsuchagency/orkestra#8]
For longer running tasks, or which may require GPU or more resources, AWS Lambda functions may not be sufficient.

Is orkestra's current architecture capable of generating and dispatching AWS Batch job definitions? How hard would it be to implement such capability?

I suppose the Batch environment setup (job queue etc.) could be left to the user. orkestra could act more as generator for Step Functions definitions.

**Comment by knowsuchagency** [comment]
Although I haven't yet tested, it should be possible to compose a [batch task](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_stepfunctions_tasks/BatchSubmitJob.html) at the CDK layer like in [this example](https://www.knowsuchagency.com/orkestra/examples/cdk_orchestration/).

I'll try it out and throw an example up soon.

**Comment by ogoid** [comment]
I've love an example, thanks. I have no experience with Python's CDK version and am still trying to understand how it all works.

Basically I'm looking for a workflow library integrated with AWS API Gateway/Lambda, Batch and Step Functions, so orkestra seems very promising.

**Comment by knowsuchagency** [comment]
Hope this helps @ogoid https://www.knowsuchagency.com/orkestra/examples/batch/ 😄
